AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  offline-development-api
  
Globals:
  Function:
    Timeout: 60

Resources:
  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/orderHandler/
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /handler-test
            Method: any
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "false"
